#!/usr/bin/env python3
"""translate — today's law and beans (v0.48.0, std-vocab 32.0) written in the core's statements, by the `replaces` map.

    python3 core/translate.py levels > core/law/levels.yaml    # the bodies' levels, from the law's `complexity`
    python3 core/translate.py layers > core/law/layers.yaml    # the flow law's sources and the files' standing

The detailed levels are rows of our knowledge tree (Q3): the face keeps the two frames, reason and the said's four
levels, and every other step of the ladder is a row the face stands on — `reason` is possible on an `organism`. They are
generated from the law that has them, never typed: `complexity` names `logos` where the core says `reason`, and
`stands_on` where it says `stands`; the frame and λόγος are the face's own and are not rows."""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(ROOT, 'bin'))
import dmparse  # noqa: E402 — today's reader of today's law

LAW = os.path.join(ROOT, 'seed', 'std-vocab.md')
FACE_LEVELS = {'space-time', 'logos'}       # the face's own: the frame of bodies, and reason
RENAMED = {'logos': 'reason'}               # the law's Greek word, where the core uses the role's


def old_law(path=LAW):
    with open(path, encoding='utf-8') as fh:
        return dmparse.loads(dmparse.split_front_matter(fh.read())[0]) or {}


def _q(s):
    """A scalar as YAML writes it plainly where it can, quoted where it must be."""
    s = str(s)
    plain = s and all(c.isalnum() or c in '-_' for c in s) and s.lower() not in ('true', 'false', 'null', 'yes', 'no', 'on', 'off')
    return s if plain else '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def levels(law):
    """The text of core/law/levels.yaml: every level of `complexity` that is not the face's own, in its order."""
    out = ["# The bodies' levels: rows of our knowledge tree, the steps of the lines of bodies beside the face's own.",
           "# GENERATED by `python3 core/translate.py levels` from std-vocab " + str(law.get('version')) + "'s `complexity`;",
           "# a change is made there, or by a RULE-CHANGE that moves these rows, never by hand here.",
           "levels:"]
    for r in law.get('complexity') or []:
        lv = str(r['level'])
        if lv in FACE_LEVELS:
            continue
        stands = []
        for s in r.get('stands_on') or []:
            at = RENAMED.get(str(s['level']), str(s['level']))
            stands.append("{ at: %s, as: %s%s }" % (_q(at), _q(s['as']), f", while: {_q(s['while'])}" if s.get('while') else ''))
        out.append(f"  - {{ level: {_q(lv)}, line: {_q(RENAMED.get(str(r['line']), str(r['line'])))}, "
                   f"stands: [{', '.join(stands)}], meaning: {_q(r.get('meaning', ''))} }}")
    return '\n'.join(out) + '\n'


def layers(law, face_layers):
    """The text of core/law/layers.yaml: the flow law's sources (every layer of `layers` the face does not name) and the
    standing of files (each layer's `holds`), from the law's `layers`."""
    rows = [r for r in law.get('layers') or [] if isinstance(r, dict) and r.get('layer')]
    out = ["# The layers beside the face's own, and which files stand in which: rows of the flow law and of the layer map.",
           "# GENERATED by `python3 core/translate.py layers` from std-vocab " + str(law.get('version')) + "'s `layers`;",
           "# a change is made there, or by a RULE-CHANGE that moves these rows, never by hand here.",
           "flow_sources: [" + ', '.join(_q(r['layer']) for r in rows if r['layer'] not in face_layers) + "]",
           "standing:"]
    for r in rows:
        holds = [str(h) for h in r.get('holds') or []]
        if holds:
            out.append(f"  - {{ layer: {_q(r['layer'])}, holds: [{', '.join(_q(h) for h in holds)}] }}")
    return '\n'.join(out) + '\n'


def main(argv):
    if argv[:1] == ['levels']:
        sys.stdout.write(levels(old_law()))
        return 0
    if argv[:1] == ['layers']:
        sys.path.insert(0, ROOT)
        from core import read
        sys.stdout.write(layers(old_law(), read.data(os.path.join(HERE, 'law', 'core.yaml')).get('layers') or []))
        return 0
    print(__doc__.strip().split('\n\n')[1] if len(__doc__.split('\n\n')) > 1 else __doc__)
    return 2


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
